/*
 * generated by Xtext 2.13.0
 */
package argument


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArgumentStandaloneSetup extends ArgumentStandaloneSetupGenerated {

	def static void doSetup() {
		new ArgumentStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
