/*
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.tests

import com.google.inject.Inject
import io.typefox.xtext.langserver.example.problem.ProblemDiagram
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ProblemInjectorProvider)
class ProblemParsingTest {
	@Inject
	ParseHelper<ProblemDiagram> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			problem: CommandedBehaviour
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
